# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Release channel'     
        required: true
        default: 'release'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate build number
      id: buildnumber
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8.0.292+10'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: build/libs/
